---
  - name: set admin user distinguished name
    set_fact:
      admindn: "{{ 'admin' | userdn(domain) }}"
    tags:
      - configuration
      - packages

  - name: set default admin distinguished name
    set_fact:
      defaultadmindn: "{{ 'admin' | userdn('default') }}"
    tags:
      - configuration
      - packages

  - name: set domain distinguished name
    set_fact:
      domaindn: "{{ domain | domaindn }}"
    tags:
      - configuration
      - packages

  - include: install.yml
  - include: domains.yml
  - include: users.yml
